=== ivadla/card-generator/data/cards/en_US/Card.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Card" xmlns:tns="http://www.example.org/Card" elementFormDefault="qualified">

    <element name="card" type="tns:card"></element>
    






    <complexType name="card">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="set" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="type" maxOccurs="1" minOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="typeTemplate"
    							type="tns:typeTemplateType">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    		<element name="cost" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="potionCost" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
            <element name="costIsSpecial" type="boolean" maxOccurs="1" minOccurs="0">
    		</element>
            <element name="coinValue" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="victoryPointValue" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="text" type="tns:textType" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <simpleType name="typeTemplateType">
    	<restriction base="string">
    		<enumeration value="action"></enumeration>
    		<enumeration value="action-victory"></enumeration>
    		<enumeration value="basic-treasure"></enumeration>
    		<enumeration value="basic-victory"></enumeration>
    		<enumeration value="duration"></enumeration>
    		<enumeration value="reaction"></enumeration>
    		<enumeration value="treasure"></enumeration>
    		<enumeration value="treasure-victory"></enumeration>
    		<enumeration value="victory"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="textType">
    	<sequence>
    		<element name="line" type="tns:lineType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="lineType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="style">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="italic"></enumeration>
    						<enumeration value="bold"></enumeration>
    						<enumeration value="separator"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== ivadla/card-generator/data/cards/en_US/hinterlands/inn.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Inn</name>
    <set>hinterlands</set>
    <type typeTemplate="action">Action</type>
    <cost>5</cost>
    <text>
        <line style="bold">+2 Cards</line>
        <line style="bold">+2 Actions</line>
        <line>Discard 2 cards.</line>
        <line>When you gain this, look through your discard pile (including this), reveal any number of Action cards from it, and shuffle them into your deck.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/cornucopia/horn of plenty.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Horn of Plenty</name>
    <set>cornucopia</set>
    <type typeTemplate="treasure">Treasure</type>
    <cost>5</cost>
    <coinValue>0</coinValue>
    <text>
        <line>When you play this, gain a card costing up to $1$ per differently named card you have in play, counting this. If it's a Victory card, trash this.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/cornucopia/diadem.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Diadem</name>
    <set>cornucopia</set>
    <type typeTemplate="treasure">Treasure - Prize</type>
    <cost>0</cost>
    <costIsSpecial>true</costIsSpecial>
    <coinValue>2</coinValue>
    <text>
        <line>When you play this, +$1$ per unused Action you have</line>
        <line>(Action, not Action card).</line>
        <line></line>
        <line style="italic">(This is not in the Supply.)</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/hinterlands/cache.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Cache</name>
    <set>hinterlands</set>
    <type typeTemplate="treasure">Treasure</type>
    <cost>5</cost>
    <coinValue>3</coinValue>
    <text>
        <line style="separator"></line>
        <line>When you gain this, gain two Coppers.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/hinterlands/crossroads.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Crossroads</name>
    <set>hinterlands</set>
    <type typeTemplate="action">Action</type>
    <cost>2</cost>
    <text>
        <line>Reveal your hand.</line>
        <line>+1 Card per Victory card revealed.</line>
        <line>If this is the first time you played a Crossroads this turn, +3 Actions.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/cornucopia/princess.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Princess</name>
    <set>cornucopia</set>
    <type typeTemplate="action">Action - Prize</type>
    <cost>0</cost>
    <costIsSpecial>true</costIsSpecial>
    <text>
        <line style="bold">+1 Buy</line>
        <line style="separator">________________</line>
        <line>While this is in play, cards cost $2$ less, but not less than $0$.</line>
        <line></line>
        <line style="italic">(This is not in the Supply.)</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/prosperity/bishop.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Bishop</name>
    <set>prosperity</set>
    <type typeTemplate="action">Action</type>
    <cost>4</cost>
    <text>
        <line>+$1$</line>
        <line>+1%VP%</line>
        <line>Trash a card from your hand. +%VP% equal to half its cost in coins, rounded down.</line>
        <line>Each other player may trash a card from his hand.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/alchemy/herbalist.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Herbalist</name>
    <set>alchemy</set>
    <type typeTemplate="action">Action</type>
    <cost>2</cost>
    <text>
        <line>+1 Buy</line>
        <line>+1 Coin</line>
        <line>When you discard this from play, you may put one of your Treasures from play on top of your deck.</line>
    </text>
</card>
