=== ivadla/card-generator/data/cards/en_US/Card.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Card" xmlns:tns="http://www.example.org/Card" elementFormDefault="qualified">

    <element name="card" type="tns:card"></element>
    






    <complexType name="card">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="set" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="type" maxOccurs="1" minOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="typeTemplate"
    							type="tns:typeTemplateType">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    		<element name="cost" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="potionCost" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
            <element name="costIsSpecial" type="boolean" maxOccurs="1" minOccurs="0">
    		</element>
            <element name="coinValue" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="victoryPointValue" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="text" type="tns:textType" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <simpleType name="typeTemplateType">
    	<restriction base="string">
    		<enumeration value="action"></enumeration>
    		<enumeration value="action-victory"></enumeration>
    		<enumeration value="basic-treasure"></enumeration>
    		<enumeration value="basic-victory"></enumeration>
    		<enumeration value="duration"></enumeration>
    		<enumeration value="reaction"></enumeration>
    		<enumeration value="treasure"></enumeration>
    		<enumeration value="treasure-victory"></enumeration>
    		<enumeration value="victory"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="textType">
    	<sequence>
    		<element name="line" type="tns:lineType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="lineType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="style">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="italic"></enumeration>
    						<enumeration value="bold"></enumeration>
    						<enumeration value="separator"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== ivadla/card-generator/data/cards/en_US/cornucopia/trusty steed.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Trusty Steed</name>
    <set>cornucopia</set>
    <type typeTemplate="action">Action - Prize</type>
    <cost>0</cost>
    <costIsSpecial>true</costIsSpecial>
    <text>
        <line>Choose two: +2 Cards; +2 Actions; +$2$; gain 4 Silvers and put your deck into your discard pile.</line>
        <line>(The choices must be different.)</line>
        <line></line>
        <line style="italic">(This is not in the Supply.)</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/seaside/navigator.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Navigator</name>
    <set>seaside</set>
    <type typeTemplate="action">Action</type>
    <cost>4</cost>
    <text>
        <line>+$2$</line>
        <line></line>
        <line>Look at the top 5 cards of your deck. Either discard all of them, or put them back on top of your deck in any order.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/hinterlands/oasis.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Oasis</name>
    <set>hinterlands</set>
    <type typeTemplate="action">Action</type>
    <cost>3</cost>
    <text>
        <line style="bold">+1 Card</line>
        <line style="bold">+1 Action</line>
        <line>+$1$</line>
        <line>Discard a card.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/prosperity/goons.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Goons</name>
    <set>prosperity</set>
    <type typeTemplate="action">Action - Attack</type>
    <cost>6</cost>
    <text>
        <line style="bold">+1 Buy</line>
        <line style="bold">+$2$</line>
        <line>Each other player discards down to 3 cards in hand.</line>
        <line style="separator">----------</line>
        <line>While this is in play, when you buy a card, +1%VP%.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/hinterlands/spice merchant.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Spice Merchant</name>
    <set>hinterlands</set>
    <type typeTemplate="action">Action</type>
    <cost>4</cost>
    <text>
        <line>You may trash a Treasure from your hand. If you do, choose one:</line>
        <line>+2 Cards and +1 Action;</line>
        <line>or +$2$ and +1 Buy.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/promo/black market.xml
<?xml version="1.0" encoding="UTF-8"?><card xsi:noNamespaceSchemaLocation="../Card.xsd">
	<name>Black Market</name>
	<set>promo</set>
	<!--Possible Values for typeTemplate are action, action-victory, duration, reaction, treasure, treasure-victory and victory-->
	<type typeTemplate="action">Action</type>
	<cost>3</cost>
	<text>
		<line>+ $2$</line>
		<line>Reveal the top 3 cards of the Black Market deck. You may buy one of them immediately. Put the unbought cards on the bottom of the Black Market deck in any order.</line>
		<line style="italic">(Before the game, make a Black Market deck out of one copy of each Kingdom card not in the supply.)</line></text>
</card>

=== ivadla/card-generator/data/cards/en_US/base/militia.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Militia</name>
    <set>base</set>
    <type typeTemplate="action">Action - Attack</type>
    <cost>4</cost>
    <text>
        <line>+$2$</line>
        <line></line>
        <line>Each other player discards down to 3 cards in his hand.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/intrigue/pawn.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Pawn</name>
    <set>intrigue</set>
    <type typeTemplate="action">Action</type>
    <cost>2</cost>
    <text>
        <line>Choose two:</line>
        <line>+1 Card</line>
        <line>+1 Action</line>
        <line>+1 Buy</line>
        <line>+$1$</line>
        <line>(The choices must be different.)</line>
    </text>
</card>
