=== ivadla/card-generator/data/cards/en_US/Card.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Card" xmlns:tns="http://www.example.org/Card" elementFormDefault="qualified">

    <element name="card" type="tns:card"></element>
    






    <complexType name="card">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="set" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="type" maxOccurs="1" minOccurs="1">
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute name="typeTemplate"
    							type="tns:typeTemplateType">
    						</attribute>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    		<element name="cost" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="potionCost" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
            <element name="costIsSpecial" type="boolean" maxOccurs="1" minOccurs="0">
    		</element>
            <element name="coinValue" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="victoryPointValue" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="text" type="tns:textType" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <simpleType name="typeTemplateType">
    	<restriction base="string">
    		<enumeration value="action"></enumeration>
    		<enumeration value="action-victory"></enumeration>
    		<enumeration value="basic-treasure"></enumeration>
    		<enumeration value="basic-victory"></enumeration>
    		<enumeration value="duration"></enumeration>
    		<enumeration value="reaction"></enumeration>
    		<enumeration value="treasure"></enumeration>
    		<enumeration value="treasure-victory"></enumeration>
    		<enumeration value="victory"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="textType">
    	<sequence>
    		<element name="line" type="tns:lineType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="lineType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="style">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="italic"></enumeration>
    						<enumeration value="bold"></enumeration>
    						<enumeration value="separator"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== ivadla/card-generator/data/cards/en_US/prosperity/vault.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Vault</name>
    <set>prosperity</set>
    <type typeTemplate="action">Action</type>
    <cost>5</cost>
    <text>
        <line style="bold">+2 Cards</line>
        <line></line>
        <line>Discard any number of cards. +$1$ per card discarded.</line>
        <line>Each other player may discard 2 cards. If he does, he draws a card.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/seaside/lookout.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Lookout</name>
    <set>seaside</set>
    <type typeTemplate="action">Action</type>
    <cost>3</cost>
    <text>
        <line style="bold">+1 Action</line>
        <line></line>
        <line>Look at the top 3 cards of your deck. Trash one of them. Discard one of them. Put the other one on top of your deck.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/intrigue/bridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Bridge</name>
    <set>intrigue</set>
    <type typeTemplate="action">Action</type>
    <cost>4</cost>
    <text>
        <line style="bold">+1 Buy</line>
        <line style="bold">+$1$</line>
        <line></line>
        <line>All cards (including cards in players' hands) cost $1$ less this turn, but not less than $0$.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/prosperity/venture.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Venture</name>
    <set>prosperity</set>
    <type typeTemplate="treasure">Treasure</type>
    <cost>5</cost>
    <coinValue>1</coinValue>
    <text>
        <line>When you play this, reveal cards from your deck until you reveal a Treasure. Discard the other cards. Play that Treasure.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/hinterlands/duchess.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Duchess</name>
    <set>hinterlands</set>
    <type typeTemplate="action">Action</type>
    <cost>2</cost>
    <text>
        <line>+$2$</line>
        <line>Each player (including you) looks at the top card of his deck, and discards it or puts it back.</line>
        <line style="separator"></line>
        <line>In games using this, when you gain a Duchy, you may gain a Duchess.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/alchemy/apothecary.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Apothecary</name>
    <set>alchemy</set>
    <type typeTemplate="action">Action</type>
    <cost>2</cost>
    <potionCost>1</potionCost>
    <text>
        <line>+1 Card</line>
        <line>+1 Action</line>
        <line>Reveal the top 4 cards of your deck. Put the revealed Coppers and Potions into your hand. Put the other cards back on top in any order.</line>
    </text>
</card>

=== ivadla/card-generator/data/cards/en_US/promo/walled village.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
	<name>Walled Village</name>
	<set>promo</set>
	<!--Possible Values for typeTemplate are action, action-victory, duration, reaction, treasure, treasure-victory and victory-->
	<type typeTemplate="action">Action</type>
	<cost>4</cost>
	<text>
		<line style="bold">+ 1 Card</line>
		<line style="bold">+ 2 Actions</line>
		<line style="separator"></line>
		<line>At the start of Clean-up, if you have this and no more than one other Action card in play, you may put this on top of your deck.</line>
	</text>
</card>

=== ivadla/card-generator/data/cards/en_US/intrigue/wishing well.xml
<?xml version="1.0" encoding="UTF-8"?>
<card xsi:noNamespaceSchemaLocation="../Card.xsd">
    <name>Wishing Well</name>
    <set>intrigue</set>
    <type typeTemplate="action">Action</type>
    <cost>3</cost>
    <text>
        <line style="bold">+1 Card</line>
        <line style="bold">+1 Action</line>
        <line></line>
        <line>Name a card. Reveal the top card of your deck. If it is the named card, put it into your hand.</line>
    </text>
</card>
